{% set name = "renalsegmentor" %}
{% set version = "1.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/alexdaniel654/Renal_Segmentor/archive/v{{ version }}.tar.gz
  sha256: 8c400127f9272fd80596512cdc98c72dee32592c47d0884dcc5300b6da7e7da2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
  run:
    - python >=3.8,<4.0
    - nibabel >=5.1.0
    - numpy >=1.24.2
    - pandas >=2.0.3
    - pytest >=7.4.0
    - scikit-image >=0.20.0
    - tensorflow >=2.13.0
    - keras <3
    - wget >=3.2

test:
  imports:
    - renalsegmentor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexdaniel654/Renal_Segmentor
  summary: Segment kidneys from MRI data
  description: |
    An application and Python package to segment kidneys from 
    renal MRI data using a convolutional neural network (CNN).
    The methods used in this software are outlined in 
    Daniel AJ, et al. Automated renal segmentation in healthy 
    and chronic kidney disease subjects using a convolutional 
    neural network. Magnetic Resonance in Medicine 
    2021;86:1125–1136 doi: https://doi.org/10.1002/mrm.28768.
  license: GPL-3.0-only
  license_file: LICENSE.txt
  dev_url: https://github.com/alexdaniel654/Renal_Segmentor

extra:
  recipe-maintainers:
    - alexdaniel654
