{% set name = "renalsegmentor" %}
{% set version = "1.3.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/renalsegmentor-{{ version }}.tar.gz
  sha256: 04af5ecf9b1d08f5d1ffc850c455820e68091ac6db1b3e9bc9c9d9beeec6db07

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8,<3.10
  run:
    - nibabel >=4.0.1
    - numpy >=1.23.1
    - pandas >=1.4.3
    - pytest >=7.1.2
    - python >=3.8,<3.10
    - scikit-image >=0.19.3
    - tensorflow >=2.6.0
    - pywget >=3.2

test:
  imports:
    - renalsegmentor
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alexdaniel654/Renal_Segmentor
  summary: Segment kidneys from MRI data
  description: |
    An application and Python package to segment kidneys from 
    renal MRI data using a convolutional neural network (CNN).
    The methods used in this software are outlined in 
    Daniel AJ, et al. Automated renal segmentation in healthy 
    and chronic kidney disease subjects using a convolutional 
    neural network. Magnetic Resonance in Medicine 
    2021;86:1125–1136 doi: https://doi.org/10.1002/mrm.28768.
  dev_url: https://github.com/alexdaniel654/Renal_Segmentor
  license: GPL-2.0-or-later
  license_file:
    - LICENSE.txt

extra:
  recipe-maintainers:
    - alexdaniel654
